import json
import os

issues = [
    {
        "title": "Adversarial Review: SQLite Embedding Cache I/O locks (Scaling Bottleneck)",
        "body": "## Finding\nSQLite Embedding Cache (`embeddings.db`) I/O locks create a severe scaling bottleneck at 10x scale.\n\n## Current Assumption\nThe current design assumes that local, synchronous database queries will easily scale to support parallel concurrent queries and scaling load.\n\n## Attack Scenario\nAn attacker sends a high volume of queries (or simply a high volume of normal concurrent requests occur), leading to database lock contention. The system tries to serialize concurrent writes or blocks reads, causing the system to lock up or reject requests.\n\n## Blast Radius\nThe entire daemon halts or significantly degrades in performance, unable to process memory retrieval or embeddings for any agent, leading to a system-wide denial-of-service.\n\n## Recommended Structural Change\nDecouple the embedding cache from a simple SQLite database or implement proper write-ahead logging (WAL) / connection pooling with async yields. Alternatively, move high-throughput embedding caches to an in-memory key-value store (like Redis or a distributed memcached equivalent) before persisting to disk."
    },
    {
        "title": "Adversarial Review: Single-Port API Gateway shared `reqwest::Client` contention (Single Point of Failure)",
        "body": "## Finding\nThe Mythrax 3.0 Single-Port API Gateway operates on port 8090 and uses a shared static auth token via `X-Mythrax-Token` and `Authorization` headers, and a shared `reqwest::Client` instance (e.g. in `get_http_client`), creating a single point of failure.\n\n## Current Assumption\nThe current design assumes a single shared client and a static, shared auth token is sufficient for a localized daemon architecture.\n\n## Attack Scenario\nAn attacker compromises the static token (since it's shared across all clients) and gains full access to all API operations. Concurrently, if the single `reqwest::Client` connection pool is exhausted or encounters a deadlock/socket leak under load, it brings down all HTTP and external API communication.\n\n## Blast Radius\nComplete compromise of the daemon (all agents and memory) if the token is leaked. Total denial-of-service for all external communications if the HTTP client socket pool is exhausted.\n\n## Recommended Structural Change\nImplement dynamic, scoped, short-lived tokens per session/agent instead of a single static `X-Mythrax-Token`. Replace the single static `reqwest::Client` with a robust, partitioned connection pool with per-route limits and circuit breakers."
    },
    {
        "title": "Adversarial Review: Streaming-to-Disk Cognitive Pipeline writing to Obsidian Vault (Orchestration/Scaling Risk)",
        "body": "## Finding\nThe Streaming-to-Disk Cognitive Pipeline writing to Obsidian Vault markdown files will fail under 10x scale.\n\n## Current Assumption\nThe system assumes the local file system (writing to Obsidian Vault markdown files) can keep up with the I/O demands of high-throughput cognitive pipelines without causing locking or disk I/O bottlenecks.\n\n## Attack Scenario\nUnder heavy load (e.g. many agents running concurrently), the pipeline generates a massive number of small file writes. The OS file system struggles to handle the concurrent writes, leading to I/O starvation and degraded system performance. An attacker can intentionally trigger frequent episodic turnovers to amplify this.\n\n## Blast Radius\nDisk I/O becomes a bottleneck, slowing down not only the agent pipelines but the entire host OS. The daemon may crash due to file handle exhaustion or I/O timeouts.\n\n## Recommended Structural Change\nImplement a buffered write queue or a virtual file system layer for the Obsidian Vault. Batch file system writes asynchronously or shift the canonical storage to a high-performance document database, exporting to Markdown only on demand."
    },
    {
        "title": "Adversarial Review: Eval framework in `evals/swebench/` tests only happy paths (Eval Robustness)",
        "body": "## Finding\nThe evaluation framework in `evals/swebench/` solely focuses on verified, functional 'happy paths' (SWE-bench coding benchmarks) and fails to test adversarial input robustness or security boundaries.\n\n## Current Assumption\nThe current assumption is that if an LLM agent can pass functional coding benchmarks (SWE-bench), it is safe and robust enough for production.\n\n## Attack Scenario\nAn attacker provides malicious inputs (e.g., prompt injections, directory traversal attempts, or logic bomb code) to the system. Because the eval framework never tests these scenarios, the system accepts the malicious input, leading to unauthorized code execution, data exfiltration, or system compromise.\n\n## Blast Radius\nComplete compromise of the agent's operating environment and any connected systems or data, as security boundaries were never properly evaluated.\n\n## Recommended Structural Change\nIntroduce adversarial datasets into the `evals/` framework. Include tests for prompt injection, jailbreaking, resource exhaustion, and unauthorized access attempts. Fail the build if the system cannot securely handle these adversarial inputs."
    },
    {
        "title": "Adversarial Review: Unbounded recursion risk in Temporal Expansion Graph (Orchestration Risk)",
        "body": "## Finding\nIn `mythrax-core` (specifically `db/crud_operations.rs`), the use of Sliding Window Caps (e.g., 1,000-element `VecDeque`) and `LIMIT 50` constraints per hop level during temporal expansion graph traversals creates an unbounded recursion risk. A depth-3 traversal can yield 125,000 nodes, leading to potential denial-of-service via adversarial memory graphs.\n\n## Current Assumption\nThe assumption is that a fixed `LIMIT 50` per node expansion is sufficient to prevent unbounded memory growth and graph explosion.\n\n## Attack Scenario\nAn attacker creates a dense, highly interconnected set of episodic memories. When the system performs a temporal expansion graph traversal (e.g., depth 3), the query expands exponentially ($50^3 = 125,000$ nodes), consuming excessive CPU and memory resources, causing a denial of service.\n\n## Blast Radius\nDenial of service for the memory retrieval system. The daemon may crash due to out-of-memory errors or CPU exhaustion.\n\n## Recommended Structural Change\nImplement a global threshold on the total number of nodes visited during graph traversal (e.g., max 1,000 nodes total), regardless of the per-hop limit. Use a priority queue to explore the most relevant edges first, rather than a naive breadth-first expansion."
    },
    {
        "title": "Adversarial Review: Prompt Injection in Episodic Memory Hooks (Orchestration Risk)",
        "body": "## Finding\nFailure to properly sanitize external inputs (user inputs, API tool results) before storing them in prompt-visible episodic memory (e.g., in `mythrax-core/src/hooks/precompact.rs`).\n\n## Current Assumption\nThe system assumes that episodic memory and tool outputs are safe and can be directly included in prompts without sanitization.\n\n## Attack Scenario\nAn attacker provides input containing control tokens like `<|`, `|>`, or code block backticks. The system stores this in episodic memory. Later, when the memory is retrieved and injected into a prompt, the control tokens hijack the LLM's parsing logic, causing it to execute attacker-controlled commands or leak information.\n\n## Blast Radius\nComplete agent compromise via cross-session prompt injection. The attacker can control the agent's actions in future sessions.\n\n## Recommended Structural Change\nImplement a strict sanitization layer for all external inputs before storing them in memory or injecting them into prompts. Replace or escape control tokens and ensure strong boundary markers are used in prompt templates."
    }
]

os.makedirs("issues", exist_ok=True)
for i, issue in enumerate(issues):
    with open(f"issues/issue_{i+1}.md", "w") as f:
        f.write(f"---\nlabels: architecture-review, adversarial\n---\n# {issue['title']}\n\n{issue['body']}")
